export const COUNTRIES = [
  { code: 'US', flag: '🇺🇸', name: 'United States' },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada' },
  { code: 'AU', flag: '🇦🇺', name: 'Australia' },
  { code: 'FR', flag: '🇫🇷', name: 'France' },
  { code: 'DE', flag: '🇩🇪', name: 'Germany' },
  { code: 'IT', flag: '🇮🇹', name: 'Italy' },
  { code: 'ES', flag: '🇪🇸', name: 'Spain' },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico' },
  { code: 'IN', flag: '🇮🇳', name: 'India' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan' },
  { code: 'KR', flag: '🇰🇷', name: 'South Korea' },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria' },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina' },
  { code: 'CO', flag: '🇨🇴', name: 'Colombia' },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands' },
  { code: 'SE', flag: '🇸🇪', name: 'Sweden' },
  { code: 'NO', flag: '🇳🇴', name: 'Norway' },
  { code: 'PL', flag: '🇵🇱', name: 'Poland' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal' },
  { code: 'RU', flag: '🇷🇺', name: 'Russia' },
  { code: 'CN', flag: '🇨🇳', name: 'China' },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines' },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia' },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan' },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh' },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt' },
  { code: 'GH', flag: '🇬🇭', name: 'Ghana' },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya' },
  { code: 'TR', flag: '🇹🇷', name: 'Turkey' },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia' },
  { code: 'AE', flag: '🇦🇪', name: 'UAE' },
  { code: 'NZ', flag: '🇳🇿', name: 'New Zealand' },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore' },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia' },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand' },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam' },
  { code: 'CL', flag: '🇨🇱', name: 'Chile' },
  { code: 'PE', flag: '🇵🇪', name: 'Peru' },
  { code: 'RO', flag: '🇷🇴', name: 'Romania' },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgium' },
  { code: 'CH', flag: '🇨🇭', name: 'Switzerland' },
  { code: 'AT', flag: '🇦🇹', name: 'Austria' },
  { code: 'DK', flag: '🇩🇰', name: 'Denmark' },
  { code: 'FI', flag: '🇫🇮', name: 'Finland' },
  { code: 'IE', flag: '🇮🇪', name: 'Ireland' },
  { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic' },
  { code: 'HU', flag: '🇭🇺', name: 'Hungary' },
  { code: 'GR', flag: '🇬🇷', name: 'Greece' },
  { code: 'IL', flag: '🇮🇱', name: 'Israel' },
  { code: 'OTHER', flag: '🌍', name: 'Other / Not listed' },
]

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c.name]))
